name: Mean cicd pipeline

on:
  push:
    branches: [ main ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./frontend/package-lock.json
    
    # Frontend: Install, Test, Build
    - name: Frontend - Install
      working-directory: ./frontend
      run: npm ci

    - name: Frontend - Test
      working-directory: ./frontend
      run: npm run test -- --watch=false --browsers=ChromeHeadless || true
    
    - name: Frontend - Build
      working-directory: ./frontend
      run: npm run build
      
    # Backend: Install, Test, Build 
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: ./backend/package.json

    - name: Backend - Install
      working-directory: ./backend
      run: npm install
      
    - name: Backend - Test
      working-directory: ./backend
      run: npm test
      
    # Build Docker Images (always on push)
    - name: Build Frontend Image
      run: |
          docker builder prune -f
          docker build \
              --no-cache \
              -t mean-frontend:latest \
              -f frontend/Dockerfile \
                frontend/

    - name: Build Backend Image
      run: docker build -t mean-backend:latest -f backend/dockerfile .
    
    # Push to Docker Hub (always on main push)
    - name: Login & Push Images
      run: |
        echo '${{ secrets.DOCKERHUB_TOKEN }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker tag mean-frontend:latest ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest
        docker tag mean-backend:latest ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-frontend:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mean-backend:latest

    # setting up vm to deploy

    - name: Deploy to VM
      uses: appleboy/ssh-action@v1.0.3
      with:
       host: ${{ secrets.VM_IP }}
       username: ${{ secrets.VM_USER }}
       key: ${{ secrets.VM_SSH_KEY }}
       port: 22
       script: | 
          cd /meanproject && \
          git pull origin main && \
          docker compose pull && \
          docker compose down && \
          docker compose up -d && \
          docker image prune -f


       